### PR TITLE
Treat Earmark Errors Graceously

### PR DESCRIPTION
**Pull request by RobertDober**
Hello always good to see Earmark being used outside of ex_doc too :grin:

Maybe you want to do something along these lines... I am not good with the front end so I guess you do not want to merge this as such, but maybe this PR is still useful.

KR
Robert

### CODE REVIEW

**Comment by jonklein** [comment]
Thank you for submitting this, and thank you for your work on Earmark!  I'll incorporate these changes, but want take a closer look at the UX around markdown errors first, so not going to merge quite yet.

**Comment by RobertDober** [comment]
of course that was my idea, sorry for not having done this myself.
This is an interesting project you have here, could help Elixir's popularity a lot good luck!

**Comment by jonklein** [comment]
Incorporated this with some frontend tweaks:

Screen Shot 2020-12-30 at 5 23 43 PM

**Comment by RobertDober** [comment]
Nice, Happy New Year

**Pull request merged**
